from enum import StrEnum


class ValidityStatus(StrEnum):
    VALIDATED = "VALIDATED"
    SUPPORTED = "SUPPORTED"
    UNVERIFIED = "UNVERIFIED"
    REVALIDATION_REQUIRED = "REVALIDATION REQUIRED"
    DRIFTED = "DRIFTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT EVIDENCE"


class Outcome(StrEnum):
    SUCCESS = "SUCCESS"
    PARTIAL_IMPROVEMENT = "PARTIAL IMPROVEMENT"
    FAILURE = "FAILURE"


class MemoryOperation(StrEnum):
    RETAIN = "RETAIN"
    RECALL = "RECALL"
    REFLECT = "REFLECT"
    VALIDITY = "VALIDITY"
